#!/bin/sh

if [ 1 -gt $# ]
then
	echo "Usage: setup path-to-psql"
	exit 
fi

path=$1

echo "    - setting up environment using path $path  "

export PATH=$PATH:$path

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$path/lib

echo "    - starting postgres backend .. "

echo "      -- introduce postgres passwd "

su postgres -c "./atpostgres $path"

echo "     -- server response: "

cat /home/postgres/errorlog.txt

# raluca
# export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/pgsql/lib:./  ; export PATH=$PATH:/usr/local/pgsql/bin/

#farm10
#

# caneland
# export PATH=/home/raluca/EncryptDB/EncryptDB/dist/bin/:$PATH ;  export LD_LIBRARY_PATH=/home/raluca/EncryptDB/EncryptDB/dist/lib:$LD_LIBRARY_PATH ; export PGDATA=/space2/raluca/data ; export PGPORT=5432

# qubit
# export PATH=/usr/local/pgsql/bin/:$PATH ; export LD_LIBRARY_PATH=/usr/local/pgsql/lib:$LD_LIBRARY_PATH ; 
# export PGDATA=/usr/local/pgsql/data ; export PGPORT=5432

#specific: address of server, function adresses, 
