CREATE FUNCTION decrypt_int_sem RETURNS INTEGER SONAME 'edb.so';
CREATE FUNCTION decrypt_int_det RETURNS INTEGER SONAME 'edb.so';
CREATE FUNCTION encrypt_int_det RETURNS INTEGER SONAME 'edb.so';
CREATE FUNCTION decrypt_text_sem RETURNS STRING SONAME 'edb.so';
CREATE FUNCTION search RETURNS INTEGER SONAME 'edb.so';
CREATE AGGREGATE FUNCTION agg RETURNS STRING SONAME 'edb.so';
CREATE FUNCTION func_add_set RETURNS STRING SONAME 'edb.so';
